logLevel: "debug"
serverManager:
  serveRetryDelay: "2000ms"
  serverOptions:
  - port: 50052
    connectionTimeout: "120000ms"
    maxRecvMsgSize: 4000000
    tlsConfig:
      certFile: /mount/secrets/server.crt
      keyFile: /mount/secrets/server.key
      caFile: /mount/secrets/ca.crt
      skipVerify: false