apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Values.commonName }}
  subject:
    organizations:
      - {{ .Values.organization.name }}
    organizationalUnits:
      - {{ .Values.organization.units }}
  secretName: {{ .Values.commonName }}-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io