apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  secretName: internal-cert-secret
  duration: 24h
  renewBefore: 12h
  issuerRef:
    name: selfsigned-issuer
  commonName: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
  - {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
