# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches-ignore:
      - "^main$"
      - "^feature$"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Build
        run: go build -C userservice -v ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        working-directory: userservice
        run: golangci-lint run --allow-parallel-runners --exclude-dirs generated --show-stats -v
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: source ./scripts/test.sh
